services:
  web:
    volumes:
      - '../../../www:/var/www/html/'
    ports:
      - '23000:80'
    restart: 'always'
    stdin_open: true
    tty: true
    logging:
      options:
        max-file: '5'
        max-size: '10m'
    build:
      context: '../../../'
      dockerfile: '.wappler/targets/Development/web/Dockerfile'
